spring:
  profiles:
    include: secret
    active: local
  datasource:
    platform: h2
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:fooding
      username: sa
      password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: info
  # org.hibernate.type: trace
